---
npm_global_packages:
  - prettier
  - stylelint
  - typescript
  - http-server
  - js-beautify
  - shadow-cljs
  - bash-language-server
  - yaml-language-server
  - typescript-language-server
  - vscode-langservers-extracted
  - "@github/copilot-language-server"
  - "@ansible/ansible-language-server"

git_user_email: "bxsr@proton.me"

