---
- name: Install Copr Dependencies
  become: true
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  loop:
    - dejan/lazygit
    - scottames/ghostty
    - rustyclanker/lua-language-server

- name: Install DBeaver
  become: true
  dnf:
    name: https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm
    state: latest
    disable_gpg_check: yes

- name: Install Dependencies
  become: true
  dnf:
    name:
      - gh
      - git
      - zsh
      - gcc
      - curl
      - grip
      - tree
      - tidy
      - cmake
      - shfmt
      - unzip
      - pdftk
      - sqlite
      - neovim
      - rlwrap
      - direnv
      - pandoc
      - fd-find
      - ghostty
      - ripgrep
      - lazygit
      - opentofu
      - cpanminus
      - gmp-devel
      - zlib-devel
      - shellcheck
      - glibc-devel
      - python3-pip
      - openssl-devel
      - libyaml-devel
      - readline-devel
      - fira-code-fonts
      - lua-language-server
    state: latest
    update_cache: true
  notify:
    - event_download_ohmyzsh
    - event_install_ohmyzsh

- name: Install Perl Dependencies
  become: true
  community.general.cpanm:
    name: "{{ item }}"
  loop:
    - DBI
    - DBD::SQLite
    - App::Sqitch

- name: Install Brave
  shell: curl -fsS https://dl.brave.com/install.sh | sh
  args:
    creates: "/usr/bin/brave-browser"

- name: Install Ohmyzsh
  block:
    - name: Install Ohmyzsh - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh.sh
        mode: 0777
    - name: Install Ohmyzsh - Run Installer
      shell: |
        echo "Y" | sh /tmp/ohmyzsh.sh
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
