---
- name: Install Dependencies
  become: true
  community.general.pacman:
    name:
      - fd
      - git
      - zsh
      - 0ad
      - gcc
      - npm
      - curl
      - tree
      - tidy
      - make
      - cmake
      - shfmt
      - unzip
      - pdftk
      - nodejs
      - sqlite
      - neovim
      - stylua
      - duckdb
      - rlwrap
      - direnv
      - pandoc
      - dbeaver
      - ghostty
      - ripgrep
      - lazygit
      - opentofu
      - base-devel
      - github-cli
      - shellcheck
      - ttf-fira-code
      - lua-language-server
    state: latest
    update_cache: true
  notify:
    - event_download_ohmyzsh
    - event_install_ohmyzsh

- name: Install Npm Dependencies
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
    force: true
    state: latest
  loop: "{{ npm_global_packages }}"

- name: Clone Fennel Lsp
  ansible.builtin.git:
    repo: https://git.sr.ht/~xerool/fennel-ls
    dest: "{{ ansible_facts['user_dir'] }}/.local/src/fennel-ls"
    depth: 1

- name: Build Fennel Lsp
  ansible.builtin.command: make install PREFIX={{ ansible_facts['user_dir'] }}/.local
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/.local/src/fennel-ls"
    creates: "{{ ansible_facts['user_dir'] }}/.local/bin/fennel-ls"

- name: Install Ollama
  become: true
  shell: curl -fsSL https://ollama.com/install.sh | sh
  args:
    creates: "/usr/local/bin/ollama"

- name: Install Opencode
  shell: curl -fsSL https://opencode.ai/install | bash
  args:
    creates: "{{ ansible_facts['user_dir'] }}/.local/bin/opencode"

- name: Ensure Coursier Bin Directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.local/share/coursier/bin"
    state: directory
    mode: 0755

- name: Download Coursier Launcher
  ansible.builtin.get_url:
    url: https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz
    dest: /tmp/cs.gz
    mode: "0644"
  changed_when: false

- name: Install Coursier
  ansible.builtin.shell: gunzip -c /tmp/cs.gz > cs
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/.local/share/coursier/bin"
    creates: "{{ ansible_facts['user_dir'] }}/.local/share/coursier/bin/cs"
