---
- name: Install Dependencies
  community.general.homebrew:
    name:
      - fd
      - gh
      - zsh
      - git
      - gmp
      - gcc
      - curl
      - grip
      - tree
      - cmake
      - shfmt
      - unzip
      - pandoc
      - neovim
      - libtool
      - lazygit
      - ripgrep
      - ghostty
      - readline
      - openssl@3
      - shellcheck
      - font-fira-code
    state: latest
  notify:
    - event_download_ohmyzsh
    - event_install_ohmyzsh

