---
- name: Install Dependencies
  community.general.homebrew:
    name:
      - node
      - fd
      - gh
      - zsh
      - git
      - gmp
      - gcc
      - curl
      - grip
      - tree
      - cmake
      - shfmt
      - unzip
      - pandoc
      - duckdb
      - neovim
      - stylua
      - libtool
      - lua-language-server
      - lazygit
      - ripgrep
      - ghostty
      - readline
      - openssl@3
      - shellcheck
      - font-fira-code
    state: latest
  notify:
    - event_download_ohmyzsh
    - event_install_ohmyzsh

- name: Install Npm Dependencies
  community.general.npm:
    name: "{{ item }}"
    global: true
    force: true
    state: latest
  loop: "{{ npm_global_packages }}"

- name: Install Common Cask Dependencies
  community.general.homebrew_cask:
    name:
      - arc
      - ollama-app
    state: latest
