---
- name: Install Dependencies
  community.general.homebrew:
    name:
      - entr
      - lima
      - direnv
      - sqlite
      - tofu-ls
      - luajit
      - luarocks
      - opentofu
      - dbeaver-community
      - lua-language-server
    state: latest

- name: Install Common Cask Dependencies
  community.general.homebrew_cask:
    name:
      - claude-code
    state: latest
  notify:
    - event_download_ohmyzsh
    - event_install_ohmyzsh
