---
- name: Enable Repositories On Brew
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - anomalyco/tap

- name: Install Dependencies
  community.general.homebrew:
    name:
      - rlwrap
      - direnv
      - sqlite
      - tofu-ls
      - opencode
      - opentofu
      - dbeaver-community
    state: latest

- name: Install Common Cask Dependencies
  community.general.homebrew_cask:
    name:
      - balenaetcher
    state: latest
