---
- name: Enable Repositories On Brew
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - clojure/tools
    - weavejester/brew
    - clojure-lsp/brew
    - coursier/formulas

- name: Trust Non-Official Brew Taps
  ansible.builtin.command: "brew trust --tap {{ item }}"
  changed_when: false
  loop:
    - clojure/tools
    - weavejester/brew
    - clojure-lsp/brew
    - coursier/formulas

- name: Install Dependencies
  community.general.homebrew:
    name:
      - cljfmt
      - clojure
      - coursier
      - leiningen
      - clojure-lsp-native
    state: latest
