---
- name: Install Dependencies
  become: "{{ ansible_facts['os_family'] == 'Archlinux' }}"
  package:
    name:
      - lua
      - qpdf
      - luajit
      - fnlfmt
      - fennel
      - podman
      - poppler
      - poppler-glib
      - ripgrep
      - tree-sitter-cli
    state: latest
