---
- name: Install Dependencies
  package:
    name:
      - npm
    state: latest

- name: Install Npm Dependencies
  community.general.npm:
    name: "{{ item }}"
    global: true
    force: true
    state: latest
  loop:
    - elm
    - elm-test
    - elm-format
    - prettier
    - typescript
    - bash-language-server
    - yaml-language-server
    - typescript-language-server
    - vscode-langservers-extracted
    - "@github/copilot-language-server"
    - "@ansible/ansible-language-server"
